apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapps.fullname" . }}-myapp
  labels:
    app: myapp
  {{- include "myapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.myapp.type }}
  selector:
    app: myapp
    {{- include "myapps.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.myapp.ports | toYaml | nindent 2 }}