apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: web-deployment
  path: replicas.yaml
