apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "1.5"
